//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBookingClient.BookingClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingDeatils", Namespace="http://schemas.datacontract.org/2004/07/HotelBooking.bookingService")]
    [System.SerializableAttribute()]
    public partial class BookingDeatils : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BookingDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckInDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckOutDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelBookingClient.BookingClient.Customer customerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberOfGuestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberOfRoomsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BookingDate {
            get {
                return this.BookingDateField;
            }
            set {
                if ((this.BookingDateField.Equals(value) != true)) {
                    this.BookingDateField = value;
                    this.RaisePropertyChanged("BookingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookingId {
            get {
                return this.BookingIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingIdField, value) != true)) {
                    this.BookingIdField = value;
                    this.RaisePropertyChanged("BookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CheckInDate {
            get {
                return this.CheckInDateField;
            }
            set {
                if ((this.CheckInDateField.Equals(value) != true)) {
                    this.CheckInDateField = value;
                    this.RaisePropertyChanged("CheckInDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CheckOutDate {
            get {
                return this.CheckOutDateField;
            }
            set {
                if ((this.CheckOutDateField.Equals(value) != true)) {
                    this.CheckOutDateField = value;
                    this.RaisePropertyChanged("CheckOutDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomId {
            get {
                return this.RoomIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomIdField, value) != true)) {
                    this.RoomIdField = value;
                    this.RaisePropertyChanged("RoomId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((this.TotalPriceField.Equals(value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelBookingClient.BookingClient.Customer customer {
            get {
                return this.customerField;
            }
            set {
                if ((object.ReferenceEquals(this.customerField, value) != true)) {
                    this.customerField = value;
                    this.RaisePropertyChanged("customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numberOfGuests {
            get {
                return this.numberOfGuestsField;
            }
            set {
                if ((this.numberOfGuestsField.Equals(value) != true)) {
                    this.numberOfGuestsField = value;
                    this.RaisePropertyChanged("numberOfGuests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numberOfRooms {
            get {
                return this.numberOfRoomsField;
            }
            set {
                if ((this.numberOfRoomsField.Equals(value) != true)) {
                    this.numberOfRoomsField = value;
                    this.RaisePropertyChanged("numberOfRooms");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/HotelBooking.customer")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailId {
            get {
                return this.emailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.emailIdField, value) != true)) {
                    this.emailIdField = value;
                    this.RaisePropertyChanged("emailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingStatus", Namespace="http://schemas.datacontract.org/2004/07/HotelBooking.bookingService")]
    [System.SerializableAttribute()]
    public partial class BookingStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelBookingClient.BookingClient.BookingDeatils bookingDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelBookingClient.BookingClient.BookingDeatils bookingDetails {
            get {
                return this.bookingDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.bookingDetailsField, value) != true)) {
                    this.bookingDetailsField = value;
                    this.RaisePropertyChanged("bookingDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.errorMessageField, value) != true)) {
                    this.errorMessageField = value;
                    this.RaisePropertyChanged("errorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookingClient.IBookingService")]
    public interface IBookingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/BookRoom", ReplyAction="http://tempuri.org/IBookingService/BookRoomResponse")]
        HotelBookingClient.BookingClient.BookingStatus BookRoom(HotelBookingClient.BookingClient.BookingDeatils bookingDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/BookRoom", ReplyAction="http://tempuri.org/IBookingService/BookRoomResponse")]
        System.Threading.Tasks.Task<HotelBookingClient.BookingClient.BookingStatus> BookRoomAsync(HotelBookingClient.BookingClient.BookingDeatils bookingDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/CancleBooking", ReplyAction="http://tempuri.org/IBookingService/CancleBookingResponse")]
        HotelBookingClient.BookingClient.BookingStatus CancleBooking(HotelBookingClient.BookingClient.BookingDeatils bookingDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/CancleBooking", ReplyAction="http://tempuri.org/IBookingService/CancleBookingResponse")]
        System.Threading.Tasks.Task<HotelBookingClient.BookingClient.BookingStatus> CancleBookingAsync(HotelBookingClient.BookingClient.BookingDeatils bookingDetails);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookingServiceChannel : HotelBookingClient.BookingClient.IBookingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookingServiceClient : System.ServiceModel.ClientBase<HotelBookingClient.BookingClient.IBookingService>, HotelBookingClient.BookingClient.IBookingService {
        
        public BookingServiceClient() {
        }
        
        public BookingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelBookingClient.BookingClient.BookingStatus BookRoom(HotelBookingClient.BookingClient.BookingDeatils bookingDetails) {
            return base.Channel.BookRoom(bookingDetails);
        }
        
        public System.Threading.Tasks.Task<HotelBookingClient.BookingClient.BookingStatus> BookRoomAsync(HotelBookingClient.BookingClient.BookingDeatils bookingDetails) {
            return base.Channel.BookRoomAsync(bookingDetails);
        }
        
        public HotelBookingClient.BookingClient.BookingStatus CancleBooking(HotelBookingClient.BookingClient.BookingDeatils bookingDetails) {
            return base.Channel.CancleBooking(bookingDetails);
        }
        
        public System.Threading.Tasks.Task<HotelBookingClient.BookingClient.BookingStatus> CancleBookingAsync(HotelBookingClient.BookingClient.BookingDeatils bookingDetails) {
            return base.Channel.CancleBookingAsync(bookingDetails);
        }
    }
}
