//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBookingClient.RoomClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomFilter", Namespace="http://schemas.datacontract.org/2004/07/HotelBooking.roomService")]
    [System.SerializableAttribute()]
    public partial class RoomFilter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] amenitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hotelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] amenities {
            get {
                return this.amenitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.amenitiesField, value) != true)) {
                    this.amenitiesField = value;
                    this.RaisePropertyChanged("amenities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cityName {
            get {
                return this.cityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.cityNameField, value) != true)) {
                    this.cityNameField = value;
                    this.RaisePropertyChanged("cityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hotelId {
            get {
                return this.hotelIdField;
            }
            set {
                if ((object.ReferenceEquals(this.hotelIdField, value) != true)) {
                    this.hotelIdField = value;
                    this.RaisePropertyChanged("hotelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rate {
            get {
                return this.rateField;
            }
            set {
                if ((object.ReferenceEquals(this.rateField, value) != true)) {
                    this.rateField = value;
                    this.RaisePropertyChanged("rate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomStatus", Namespace="http://schemas.datacontract.org/2004/07/HotelBooking.roomService")]
    [System.SerializableAttribute()]
    public partial class RoomStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messsageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelBookingClient.RoomClient.Room[] roomsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string messsage {
            get {
                return this.messsageField;
            }
            set {
                if ((object.ReferenceEquals(this.messsageField, value) != true)) {
                    this.messsageField = value;
                    this.RaisePropertyChanged("messsage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelBookingClient.RoomClient.Room[] rooms {
            get {
                return this.roomsField;
            }
            set {
                if ((object.ReferenceEquals(this.roomsField, value) != true)) {
                    this.roomsField = value;
                    this.RaisePropertyChanged("rooms");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Room", Namespace="http://schemas.datacontract.org/2004/07/HotelBooking.roomService")]
    [System.SerializableAttribute()]
    public partial class Room : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string amenitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string amenities {
            get {
                return this.amenitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.amenitiesField, value) != true)) {
                    this.amenitiesField = value;
                    this.RaisePropertyChanged("amenities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rate {
            get {
                return this.rateField;
            }
            set {
                if ((object.ReferenceEquals(this.rateField, value) != true)) {
                    this.rateField = value;
                    this.RaisePropertyChanged("rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoomClient.IRoom")]
    public interface IRoom {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoom/GetRooms", ReplyAction="http://tempuri.org/IRoom/GetRoomsResponse")]
        HotelBookingClient.RoomClient.RoomStatus GetRooms(HotelBookingClient.RoomClient.RoomFilter roomfilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoom/GetRooms", ReplyAction="http://tempuri.org/IRoom/GetRoomsResponse")]
        System.Threading.Tasks.Task<HotelBookingClient.RoomClient.RoomStatus> GetRoomsAsync(HotelBookingClient.RoomClient.RoomFilter roomfilter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoomChannel : HotelBookingClient.RoomClient.IRoom, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomClient : System.ServiceModel.ClientBase<HotelBookingClient.RoomClient.IRoom>, HotelBookingClient.RoomClient.IRoom {
        
        public RoomClient() {
        }
        
        public RoomClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoomClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelBookingClient.RoomClient.RoomStatus GetRooms(HotelBookingClient.RoomClient.RoomFilter roomfilter) {
            return base.Channel.GetRooms(roomfilter);
        }
        
        public System.Threading.Tasks.Task<HotelBookingClient.RoomClient.RoomStatus> GetRoomsAsync(HotelBookingClient.RoomClient.RoomFilter roomfilter) {
            return base.Channel.GetRoomsAsync(roomfilter);
        }
    }
}
